name: Build, possibly test, and publish Docker Images

env:
  IMAGE_NAME: ${{ github.repository }}
  REGISTRY: ghcr.io


# For more details on events that trigger workflows see:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "image/**"
      - "tests/**"
      - "requirements-dev.txt"
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-publish-images:
    runs-on: self-hosted
    strategy:
        fail-fast: false
        matrix: 
          include:  
            - dockerfile: ./image/custom-datascience/Dockerfile
              image: ghcr.io/mcam10/custom-datascience
            - dockerfile: ./image/tensorflow-notebook/Dockerfile
              image: ghcr.io/mcam10/tensorflow-notebook
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set Up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dev Dependencies 📦
        run: |
          pip install --upgrade pip
          pip install --upgrade -r requirements-dev.txt

       # Run tests if you want          

#      - name: Run tests ✅
#        shell: bash    
#        run: python3 -m pytest tests.run_tests --short-image-name ${{ inputs.image }} --registry ${{ env.REGISTRY }} --owner ${{ env.OWNER }}

      - name: Log in to the Container registry 
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   

      - name: Extract metadata (tags, labels for Docker)
        id: meta
        uses: docker/metadata-action@c314eea2b27e3cb3c7d7be0618510234d8f6178e
        with:
          images: ${{ matrix.image }}

      - name: Build image 🛠
        #build depending on if branch or event name matches
        #        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
