name: Build, test, and publish Docker Images

env:
  OWNER: "malik1010"
  IMAGE_NAME: ${{ github.event.repository.name }}
  REGISTRY: ghcr.io


# For more details on events that trigger workflows see:
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
on:
  schedule:
    # Weekly, at 07:00 on Monday UTC time
    - cron: "0 7 * * 1"
  pull_request:
    paths:
      - ".github/workflows/docker.yml"
      - "image/**"
      - "tests/**"
      - "requirements-dev.txt"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/docker.yml"
      - "image/**"
      - "tests/**"
      - "requirements-dev.txt"
  workflow_dispatch:

# https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  # only cancel in-progress jobs or runs for the current workflow - matches against branch & tags
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-publish-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repo ⚡️
        uses: actions/checkout@v4

      - name: Set Up Python 🐍
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Dev Dependencies 📦
        run: |
          pip install --upgrade pip
          pip install --upgrade -r requirements-dev.txt

       # Run tests if you want          

#      - name: Run tests ✅
#        shell: bash    
#        run: python3 -m pytest tests.run_tests --short-image-name ${{ inputs.image }} --registry ${{ env.REGISTRY }} --owner ${{ env.OWNER }}

      - name: Log in to the Container registry 
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   

      - name: Extract metadata (tags, labels for Docker)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{env.IMAGE_NAME}}

      - name: Build image 🛠
        #        if: github.ref == 'refs/heads/main' || github.event_name == 'schedule'
        uses: docker/build-push-action
        with:
         context: ./image/custom-datascience
         push: true
         tags: ${{ steps.meta.outputs.labels.tags }}
         labels: ${{ steps.meta.outputs.labels }}
